[theme]
primaryColor = "#1DB954"         
backgroundColor = "#0E1117"     
secondaryBackgroundColor = "#1B1F2A"  
textColor = "#FFFFFF"            
font = "sans serif"              

[server]
headless = true
enableCORS = false

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false